
apiVersion: v1
kind: ConfigMap

metadata: 
   name: backend
   namespace: expense
data: 
  DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels: # these are replicaset labels
    app: backend
    tier: api
    project: expense
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    # these are used to select the pod to create replicas
    matchLabels:
      app: backend
      tier: api
      project: expense
  # this is pod definition
  template:
    metadata:
      # these labels belongs to pod
      labels:
        app: backend
        tier: api
        project: expense
    spec:
      containers:
      - name: backend
        image: rajesh2219/backend:v1
        envFrom:
        - configMapRef:
           name: backend
---
kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    app: backend
    tier: api
    project: expense
  ports:
  - name: backend-svc-port
    protocol: TCP
    port: 8080 # service port
    targetPort: 8080 # container port


